### ISSUE TITLE
 Problem with the plugin

### ISSUE THREAD

**Issue by NyCoSD** [Acquized/UltimateReport#3]
[EN]
Hello,
Your plugin seems very practical but I unfortunately a problem with it. Basically it works . But after disconnecting a player plugin prevents your player out of the proxy. Basically I connect and disconnect me but I remain on it. And I can confirm that it comes from you. Because when I turn off all your plugin become again normal .

Sincerely,
_NyCoSD_

[FR]
Bonjour,
Votre plugin a l'air très pratique mais j'ai malheureusement un problème avec celui-ci. En gros il fonctionne. Mais après la déconnexion d'un joueur votre plugin empêche le joueur de sortir du proxy. En gros je me connecte puis me déconnecte mais je reste dessus. Et je peux confirmer que cela vient de chez vous. Car quand je désactive votre plugin tous redeviens normal.

Amicalement,
_NyCoSD_

**Comment by Acquized** [comment]
Hello, please note that this Plugin has been Deprecated. This Project will be replaced by [ProjectRetile](https://github.com/Acquized/ProjectRetile) which has a current ETA in 1 month. I hope that for you waiting 1 month is no problem, if it is, then i'm sorry that i can't provide Support. If you need more Informations about the Deprecation of UltimateReport, visit the Main Page and read the Black Bold Text [here](https://www.spigotmc.org/resources/deprecated-ultimatereport.11364/). If you want more Information for whatever reason, feel free to open a Issue Request on the **ProjectRetile** Page. Thanks for your Understading.

-Acquized
